services:
  core:
    image: app.git.valerii.cc/valerii/gateway:latest
    container_name: core
    restart: unless-stopped
    tty: false
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro
